# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\proyetos python\prueba cursos\contar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(100, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setMinimumSize(QtCore.QSize(700, 500))
        self.frame.setMaximumSize(QtCore.QSize(700, 500))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 82, 200);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_regresar = QtWidgets.QPushButton(self.frame)
        self.bt_regresar.setGeometry(QtCore.QRect(550, 450, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.btn_actualizar = QtWidgets.QPushButton(self.frame)
        self.btn_actualizar.setGeometry(QtCore.QRect(40, 130, 121, 40))
        self.btn_actualizar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_actualizar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizar.setIcon(icon1)
        self.btn_actualizar.setIconSize(QtCore.QSize(32, 32))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 400, 35))
        self.label_8.setMinimumSize(QtCore.QSize(400, 35))
        self.label_8.setMaximumSize(QtCore.QSize(200, 30))
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 181, 35))
        self.label_9.setMinimumSize(QtCore.QSize(100, 35))
        self.label_9.setMaximumSize(QtCore.QSize(200, 30))
        self.label_9.setObjectName("label_9")
        self.label_apro = QtWidgets.QLabel(self.frame)
        self.label_apro.setGeometry(QtCore.QRect(220, 30, 181, 35))
        self.label_apro.setMinimumSize(QtCore.QSize(100, 35))
        self.label_apro.setMaximumSize(QtCore.QSize(200, 30))
        self.label_apro.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_apro.setText("")
        self.label_apro.setObjectName("label_apro")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(30, 60, 181, 35))
        self.label_13.setMinimumSize(QtCore.QSize(100, 35))
        self.label_13.setMaximumSize(QtCore.QSize(200, 30))
        self.label_13.setObjectName("label_13")
        self.label_cursando = QtWidgets.QLabel(self.frame)
        self.label_cursando.setGeometry(QtCore.QRect(220, 60, 181, 35))
        self.label_cursando.setMinimumSize(QtCore.QSize(100, 35))
        self.label_cursando.setMaximumSize(QtCore.QSize(200, 30))
        self.label_cursando.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_cursando.setText("")
        self.label_cursando.setObjectName("label_cursando")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(30, 90, 181, 35))
        self.label_14.setMinimumSize(QtCore.QSize(100, 35))
        self.label_14.setMaximumSize(QtCore.QSize(200, 30))
        self.label_14.setObjectName("label_14")
        self.label_pendiente = QtWidgets.QLabel(self.frame)
        self.label_pendiente.setGeometry(QtCore.QRect(220, 90, 181, 35))
        self.label_pendiente.setMinimumSize(QtCore.QSize(100, 35))
        self.label_pendiente.setMaximumSize(QtCore.QSize(200, 30))
        self.label_pendiente.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_pendiente.setText("")
        self.label_pendiente.setObjectName("label_pendiente")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(30, 190, 181, 35))
        self.label_12.setMinimumSize(QtCore.QSize(100, 35))
        self.label_12.setMaximumSize(QtCore.QSize(200, 30))
        self.label_12.setObjectName("label_12")
        self.lineEdit_numsem = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_numsem.setGeometry(QtCore.QRect(220, 200, 121, 20))
        self.lineEdit_numsem.setObjectName("lineEdit_numsem")
        self.btn_validar = QtWidgets.QPushButton(self.frame)
        self.btn_validar.setGeometry(QtCore.QRect(350, 190, 100, 40))
        self.btn_validar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_validar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btn_validar.setIcon(icon1)
        self.btn_validar.setIconSize(QtCore.QSize(32, 32))
        self.btn_validar.setObjectName("btn_validar")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(30, 230, 181, 35))
        self.label_15.setMinimumSize(QtCore.QSize(100, 35))
        self.label_15.setMaximumSize(QtCore.QSize(200, 30))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(30, 260, 181, 35))
        self.label_16.setMinimumSize(QtCore.QSize(100, 35))
        self.label_16.setMaximumSize(QtCore.QSize(200, 30))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(30, 290, 181, 35))
        self.label_17.setMinimumSize(QtCore.QSize(100, 35))
        self.label_17.setMaximumSize(QtCore.QSize(200, 30))
        self.label_17.setObjectName("label_17")
        self.label_semapro = QtWidgets.QLabel(self.frame)
        self.label_semapro.setGeometry(QtCore.QRect(220, 240, 181, 20))
        self.label_semapro.setMinimumSize(QtCore.QSize(100, 20))
        self.label_semapro.setMaximumSize(QtCore.QSize(200, 30))
        self.label_semapro.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_semapro.setText("")
        self.label_semapro.setObjectName("label_semapro")
        self.label_semcurs = QtWidgets.QLabel(self.frame)
        self.label_semcurs.setGeometry(QtCore.QRect(220, 270, 181, 20))
        self.label_semcurs.setMinimumSize(QtCore.QSize(100, 20))
        self.label_semcurs.setMaximumSize(QtCore.QSize(200, 30))
        self.label_semcurs.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_semcurs.setText("")
        self.label_semcurs.setObjectName("label_semcurs")
        self.label_sempen = QtWidgets.QLabel(self.frame)
        self.label_sempen.setGeometry(QtCore.QRect(220, 300, 181, 20))
        self.label_sempen.setMinimumSize(QtCore.QSize(100, 20))
        self.label_sempen.setMaximumSize(QtCore.QSize(200, 30))
        self.label_sempen.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_sempen.setText("")
        self.label_sempen.setObjectName("label_sempen")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 320, 181, 35))
        self.label_18.setMinimumSize(QtCore.QSize(100, 35))
        self.label_18.setMaximumSize(QtCore.QSize(200, 30))
        self.label_18.setObjectName("label_18")
        self.btn_validarN = QtWidgets.QPushButton(self.frame)
        self.btn_validarN.setGeometry(QtCore.QRect(350, 320, 100, 40))
        self.btn_validarN.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_validarN.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btn_validarN.setIcon(icon1)
        self.btn_validarN.setIconSize(QtCore.QSize(32, 32))
        self.btn_validarN.setObjectName("btn_validarN")
        self.lineEdit_numseN = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_numseN.setGeometry(QtCore.QRect(220, 330, 121, 20))
        self.lineEdit_numseN.setObjectName("lineEdit_numseN")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(30, 370, 191, 35))
        self.label_19.setMinimumSize(QtCore.QSize(100, 35))
        self.label_19.setMaximumSize(QtCore.QSize(200, 30))
        self.label_19.setObjectName("label_19")
        self.label_semN = QtWidgets.QLabel(self.frame)
        self.label_semN.setGeometry(QtCore.QRect(230, 380, 181, 20))
        self.label_semN.setMinimumSize(QtCore.QSize(100, 20))
        self.label_semN.setMaximumSize(QtCore.QSize(200, 30))
        self.label_semN.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}")
        self.label_semN.setText("")
        self.label_semN.setObjectName("label_semN")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contar creditos"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.btn_actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.label_8.setText(_translate("MainWindow", "Mostrar creditos"))
        self.label_9.setText(_translate("MainWindow", "Creditos Aprobados:"))
        self.label_13.setText(_translate("MainWindow", "Créditos Cusrsando:"))
        self.label_14.setText(_translate("MainWindow", "Créditos Pendientes:"))
        self.label_12.setText(_translate("MainWindow", "Ingrese el semestre"))
        self.btn_validar.setText(_translate("MainWindow", "vaidar"))
        self.label_15.setText(_translate("MainWindow", "Creditos Aprobados:"))
        self.label_16.setText(_translate("MainWindow", "Créditos Cusrsando:"))
        self.label_17.setText(_translate("MainWindow", "Créditos Pendientes:"))
        self.label_18.setText(_translate("MainWindow", "Ingrese el semestre"))
        self.btn_validarN.setText(_translate("MainWindow", "vaidar"))
        self.label_19.setText(_translate("MainWindow", "Creditos obligatorios:"))
