# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\proyetos python\prueba cursos\editar_curso.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(100, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setMinimumSize(QtCore.QSize(700, 500))
        self.frame.setMaximumSize(QtCore.QSize(700, 500))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 82, 200);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_regresar = QtWidgets.QPushButton(self.frame)
        self.bt_regresar.setGeometry(QtCore.QRect(550, 450, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.btn_editar = QtWidgets.QPushButton(self.frame)
        self.btn_editar.setGeometry(QtCore.QRect(260, 390, 141, 40))
        self.btn_editar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_editar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\escritura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar.setIcon(icon1)
        self.btn_editar.setIconSize(QtCore.QSize(32, 32))
        self.btn_editar.setObjectName("btn_editar")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 400, 35))
        self.label_8.setMinimumSize(QtCore.QSize(400, 35))
        self.label_8.setMaximumSize(QtCore.QSize(200, 30))
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 90, 412, 285))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(200, 32))
        self.label.setMaximumSize(QtCore.QSize(200, 30))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 32))
        self.label_2.setMaximumSize(QtCore.QSize(200, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 32))
        self.label_3.setMaximumSize(QtCore.QSize(200, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(200, 32))
        self.label_5.setMaximumSize(QtCore.QSize(200, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 32))
        self.label_4.setMaximumSize(QtCore.QSize(200, 30))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(200, 32))
        self.label_6.setMaximumSize(QtCore.QSize(200, 30))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(200, 32))
        self.label_7.setMaximumSize(QtCore.QSize(200, 30))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_codigo = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_codigo.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_codigo.setText("")
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.verticalLayout.addWidget(self.lineEdit_codigo)
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_nombre.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_nombre.setText("")
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.verticalLayout.addWidget(self.lineEdit_nombre)
        self.lineEdit_requisito = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_requisito.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_requisito.setText("")
        self.lineEdit_requisito.setObjectName("lineEdit_requisito")
        self.verticalLayout.addWidget(self.lineEdit_requisito)
        self.lineEdit_obli = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_obli.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_obli.setText("")
        self.lineEdit_obli.setObjectName("lineEdit_obli")
        self.verticalLayout.addWidget(self.lineEdit_obli)
        self.line_semestre = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_semestre.setMinimumSize(QtCore.QSize(200, 25))
        self.line_semestre.setText("")
        self.line_semestre.setObjectName("line_semestre")
        self.verticalLayout.addWidget(self.line_semestre)
        self.line_creditos = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_creditos.setMinimumSize(QtCore.QSize(200, 25))
        self.line_creditos.setText("")
        self.line_creditos.setObjectName("line_creditos")
        self.verticalLayout.addWidget(self.line_creditos)
        self.line_estado = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_estado.setMinimumSize(QtCore.QSize(200, 25))
        self.line_estado.setText("")
        self.line_estado.setObjectName("line_estado")
        self.verticalLayout.addWidget(self.line_estado)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(280, 20, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(430, 20, 81, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editar_curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.btn_editar.setText(_translate("MainWindow", "Editar"))
        self.label_8.setText(_translate("MainWindow", "Ingresa el codigo a editar"))
        self.label.setText(_translate("MainWindow", "Codigo"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Pre Requisito"))
        self.label_5.setText(_translate("MainWindow", "Opcionalidad"))
        self.label_4.setText(_translate("MainWindow", "Semestre"))
        self.label_6.setText(_translate("MainWindow", "Creditos"))
        self.label_7.setText(_translate("MainWindow", "Estado"))
        self.pushButton.setText(_translate("MainWindow", "Validar"))
