# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\proyetos python\[LFP]Practica1_A+_201445840\eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 177)
        MainWindow.setMinimumSize(QtCore.QSize(471, 177))
        MainWindow.setMaximumSize(QtCore.QSize(471, 177))
        MainWindow.setStyleSheet("background-color: rgb(18, 82, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_regresar.setGeometry(QtCore.QRect(320, 130, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 150, 28))
        self.label.setMinimumSize(QtCore.QSize(150, 28))
        self.label.setMaximumSize(QtCore.QSize(150, 28))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.lineEdit_codigo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_codigo.setGeometry(QtCore.QRect(220, 50, 200, 25))
        self.lineEdit_codigo.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_codigo.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";")
        self.lineEdit_codigo.setText("")
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 400, 32))
        self.label_2.setMinimumSize(QtCore.QSize(400, 32))
        self.label_2.setMaximumSize(QtCore.QSize(200, 30))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar.setGeometry(QtCore.QRect(150, 100, 141, 40))
        self.btn_eliminar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_eliminar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\1492790846-9cancel_84247.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eliminar.setIcon(icon1)
        self.btn_eliminar.setIconSize(QtCore.QSize(32, 32))
        self.btn_eliminar.setObjectName("btn_eliminar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eliminar Curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.label.setText(_translate("MainWindow", "Codigo"))
        self.label_2.setText(_translate("MainWindow", "ingrese el curso a eliminar"))
        self.btn_eliminar.setText(_translate("MainWindow", "Eliminar"))
