# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\proyetos python\prueba cursos\gestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 400)
        MainWindow.setMinimumSize(QtCore.QSize(710, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(710, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.frame_lateral = QtWidgets.QFrame(self.centralwidget)
        self.frame_lateral.setGeometry(QtCore.QRect(0, 0, 710, 400))
        self.frame_lateral.setMinimumSize(QtCore.QSize(710, 400))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_lateral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_lateral.setAutoFillBackground(False)
        self.frame_lateral.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(18, 82, 200);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout.setContentsMargins(150, -1, 150, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_lateral)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color:rgb(0,0,0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.bt_listar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_listar.setMinimumSize(QtCore.QSize(400, 40))
        self.bt_listar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bt_listar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_listar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\base-de-datos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_listar.setIcon(icon)
        self.bt_listar.setIconSize(QtCore.QSize(32, 32))
        self.bt_listar.setObjectName("bt_listar")
        self.verticalLayout.addWidget(self.bt_listar)
        self.bt_agregar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_agregar.setMinimumSize(QtCore.QSize(400, 40))
        self.bt_agregar.setToolTipDuration(0)
        self.bt_agregar.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\archivo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_agregar.setIcon(icon1)
        self.bt_agregar.setIconSize(QtCore.QSize(32, 32))
        self.bt_agregar.setObjectName("bt_agregar")
        self.verticalLayout.addWidget(self.bt_agregar)
        self.bt_editar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_editar.setMinimumSize(QtCore.QSize(400, 40))
        self.bt_editar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\encriptado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_editar.setIcon(icon2)
        self.bt_editar.setIconSize(QtCore.QSize(32, 32))
        self.bt_editar.setObjectName("bt_editar")
        self.verticalLayout.addWidget(self.bt_editar)
        self.bt_eliminar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_eliminar.setMinimumSize(QtCore.QSize(400, 40))
        self.bt_eliminar.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/encriptado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_eliminar.setIcon(icon3)
        self.bt_eliminar.setIconSize(QtCore.QSize(32, 32))
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.verticalLayout.addWidget(self.bt_eliminar)
        self.bt_regresar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_regresar.setMinimumSize(QtCore.QSize(400, 40))
        self.bt_regresar.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\prueba cursos\\pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon4)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.verticalLayout.addWidget(self.bt_regresar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu de gestion"))
        self.label.setText(_translate("MainWindow", "Elija una opcion para gestionar"))
        self.bt_listar.setText(_translate("MainWindow", "Listar Cursos"))
        self.bt_agregar.setText(_translate("MainWindow", "Agregar Curso"))
        self.bt_editar.setText(_translate("MainWindow", "Editar Curso"))
        self.bt_eliminar.setText(_translate("MainWindow", "Eliminar Curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
