# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\proyetos python\[LFP]Practica1_A+_201445840\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.frame_lateral = QtWidgets.QFrame(self.centralwidget)
        self.frame_lateral.setGeometry(QtCore.QRect(0, 40, 200, 365))
        self.frame_lateral.setMinimumSize(QtCore.QSize(200, 365))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 365))
        self.frame_lateral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_lateral.setAutoFillBackground(False)
        self.frame_lateral.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(18, 82, 200);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 9)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.bt_cargar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_cargar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_cargar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_cargar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/archivo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cargar.setIcon(icon)
        self.bt_cargar.setIconSize(QtCore.QSize(32, 32))
        self.bt_cargar.setObjectName("bt_cargar")
        self.verticalLayout_2.addWidget(self.bt_cargar)
        self.bt_gestionar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_gestionar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_gestionar.setToolTipDuration(0)
        self.bt_gestionar.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/inteligencia-artificial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_gestionar.setIcon(icon1)
        self.bt_gestionar.setIconSize(QtCore.QSize(32, 32))
        self.bt_gestionar.setObjectName("bt_gestionar")
        self.verticalLayout_2.addWidget(self.bt_gestionar)
        self.bt_contar = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_contar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_contar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/encriptado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_contar.setIcon(icon2)
        self.bt_contar.setIconSize(QtCore.QSize(32, 32))
        self.bt_contar.setObjectName("bt_contar")
        self.verticalLayout_2.addWidget(self.bt_contar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_superior = QtWidgets.QFrame(self.centralwidget)
        self.frame_superior.setGeometry(QtCore.QRect(0, 0, 700, 40))
        self.frame_superior.setMinimumSize(QtCore.QSize(700, 39))
        self.frame_superior.setMaximumSize(QtCore.QSize(700, 50))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"\n"
"\n"
"background-color: rgb(18, 82, 200);\n"
"\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_8.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMaximumSize(QtCore.QSize(35, 16777215))
        self.bt_cerrar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color:red;\n"
"\n"
"}\n"
"")
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(32, 32))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout_8.addWidget(self.bt_cerrar, 0, QtCore.Qt.AlignRight)
        self.frame_contenedor = QtWidgets.QFrame(self.centralwidget)
        self.frame_contenedor.setEnabled(True)
        self.frame_contenedor.setGeometry(QtCore.QRect(200, 40, 500, 365))
        self.frame_contenedor.setMinimumSize(QtCore.QSize(500, 365))
        self.frame_contenedor.setMaximumSize(QtCore.QSize(500, 365))
        self.frame_contenedor.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedor.setLineWidth(1)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.label_3 = QtWidgets.QLabel(self.frame_contenedor)
        self.label_3.setGeometry(QtCore.QRect(76, 51, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 12pt \"Arial Black\";\n"
"color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_contenedor)
        self.label_2.setGeometry(QtCore.QRect(76, 86, 271, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 12pt \"Arial Black\";\n"
"color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_contenedor)
        self.label_4.setGeometry(QtCore.QRect(76, 115, 181, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 12pt \"Arial Black\";\n"
"color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame_contenedor)
        self.label.setGeometry(QtCore.QRect(76, 16, 421, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 12pt \"Arial Black\";\n"
"color:rgb(255, 255, 255)\n"
"")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame_contenedor)
        self.label_5.setGeometry(QtCore.QRect(130, 140, 300, 200))
        self.label_5.setMinimumSize(QtCore.QSize(300, 200))
        self.label_5.setMaximumSize(QtCore.QSize(300, 200))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\proyetos python\\[LFP]Practica1_A+_201445840\\../../../Downloads/gui_python_pyqt5-main/gui_python_pyqt5-main/Menu Lateral desplegable/imagen_dos.png"))
        self.label_5.setScaledContents(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu Principal"))
        self.bt_cargar.setText(_translate("MainWindow", "Cargar Archivo"))
        self.bt_gestionar.setText(_translate("MainWindow", "Gestionar Cursos"))
        self.bt_contar.setText(_translate("MainWindow", "Conteo de Créditos"))
        self.label_3.setText(_translate("MainWindow", "Seccion: \"A+\""))
        self.label_2.setText(_translate("MainWindow", "Luis Humberto Lémus Pérez"))
        self.label_4.setText(_translate("MainWindow", "Carné: 201445840"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Lenguajes Formales y de programación"))
